### ISSUE TITLE
Enable multi-select for Sector > Sub-Sector > Activities 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#2]

**Comment by PeaceGeeks** [comment]
http://wimleers.com/demo/hierarchical-select/taxonomy

**Comment by fmann** [comment]
Can we verify the desired changes before making them?  

My interpretation of this is that Activity Details would go away, that all of the Activity Details would become grandchildren in the hierarchy. So we'd have Sector > Sub-Sector > (one or more activity). Is that correct?

Only one Sector / Sub-Sector is supposed to be selected per location, yes?  Like you could have 

CASH > Financial Assistance > one or more Activity

but you couldn't have 

CASH > Financial Assistance > one or more Activity
EDUCATION > Educational Opportunities > one or more Activity

for a single location, correct?

FWIW we're already running hierarchy select here, but I need to verify whether we can make it do precisely what we desire.

**Comment by fmann** [comment]
I've spent a couple of hours looking into this. I think it would be doable with a couple of patches to hierarchy select, but it is a real pain.

Before spending more time on it, can I get confirmation on the requirements?

- Is it true that only leaves can be selected? Only Activities, not Sectors or Sub-Sectors?
- Is it true that all Sub-Sectors will have Activities? And that all branches will end 3 deep, not 2 or 4 or 5?
 
Allowing more than one Sub-Sector or Sector, even, to be selected, is probably possible if we want that, but it would definitely break the JSON and the SA client.  If we are deliberate about what we want here, I can build accordingly.

**Comment by fmann** [comment]
I have a proposed fix for this on the chosen_jquery_chained branch (last commit 3a6b626ff1d6420496cac430eafd8f4dcb355e75).

Sector, Sub-sector, and Activities have become three distinct vocabularies. There are entity references pointing from the child terms up to their parent rather than using the taxonomy term hierarchies.  

Activities allows multiple values, the others are single selection.

If this approach works I will go ahead and make tweaks to the client side to support the multiple Activities.

**Comment by fmann** [comment]
Chained select support is now in place.
