### ISSUE TITLE
Enable Site Administrator (UNHCR) to manage taxonomies & add Site Admin Role

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/ServicesAdvisor-2.0#7]
@fmann - would this be easy to add?

**Comment by fmann** [comment]
Amani Admins have adequate permission for this.

**Comment by PeaceGeeks** [comment]
Agreed. I am going to move this to the backlog for the moment, but I think this is something we want to address right away once we have a contract.

**Comment by PeaceGeeks** [comment]
Need to clarify all roles and permissions. Murad as Amani Admin can already manage taxonomies.

**Comment by PeaceGeeksProjects** [comment]
Clarify to who?  The Services Advisor Backend User Guide doc (https://docs.google.com/document/d/1AnE5PL5UoIquAKXg8VGVolONJsc_o-ZmoAuInPlxFuo) describes it for the Users.as:
1. Site Administrator: managing Site Users, Service Providers  (Groups), and Picklists (Taxonomies)
2. Group Administrator managing their Group (Members & Services)
3. Group Member managing the services provided by their Group

Since Taxonomies are NOT Group related bu apply on ALL groups, I suggest they remain with the Site Coordinator (Aman Admin) role.

**Comment by PeaceGeeksProjects** [comment]
@mackh The only item remaining is for Site Administrator to be able Set Users Role to Site Administrator...

**Comment by jinng2016** [comment]
Submitted merge request #61

**Comment by PeaceGeeksProjects** [comment]
verified
